version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(cargo)"
    labels:
      - dependencies
      - rust
    groups:
      cargo-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/live-build/builder"
    target-branch: main
    schedule:
      interval: weekly
      day: tuesday
      time: "04:30"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(docker)"
    labels:
      - dependencies
      - docker
    groups:
      docker-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: wednesday
      time: "04:30"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions-minor-and-patch:
        update-types:
          - minor
          - patch
