[package]
name = "metafuse"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
adad-core = { path = "../adad-core" }

[target.'cfg(target_os = "linux")'.dependencies]
fuser = { version = "=0.18.0", default-features = false }
libc = "=0.2.186"
